spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: testdb
    password: psw1234
    driverClassName: org.h2.Driver
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
